name: resapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  google_sign_in: ^6.1.2
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.2
  flutter_facebook_auth: ^6.1.0
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/